services:
  server:
    image: ghcr.io/bg-101/aas-live-server:latest
    env_file: ./server/.env
    ports: ["3001:3001"]
    restart: unless-stopped

  client:
    image: ghcr.io/bg-101/aas-live-client:latest
    ports: ["80:8080"]
    depends_on: [server]
    restart: unless-stopped
